=== donker/YAG/Templates/Settings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 sp2 (http://www.altova.com) by Peter Donker (Bring2mind) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
 <xs:element name="templateSettings">
  <xs:annotation>
   <xs:documentation>Settings for the Gallery module</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:sequence>
    <xs:element name="templateSetting" minOccurs="0" maxOccurs="unbounded">
     <xs:complexType>
      <xs:all>
       <xs:element name="key" type="xs:string"/>
       <xs:element name="valueType">
        <xs:simpleType>
         <xs:restriction base="xs:string">
          <xs:enumeration value="string"/>
          <xs:enumeration value="dropdown"/>
          <xs:enumeration value="integer"/>
          <xs:enumeration value="truefalse"/>
          <xs:enumeration value="10"/>
          <xs:enumeration value="number"/>
         </xs:restriction>
        </xs:simpleType>
       </xs:element>
       <xs:element name="values" minOccurs="0">
        <xs:complexType>
         <xs:sequence>
          <xs:element name="value" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
         </xs:sequence>
        </xs:complexType>
       </xs:element>
       <xs:element name="defaultValue" type="xs:string"/>
      </xs:all>
     </xs:complexType>
    </xs:element>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
</xs:schema>

=== donker/YAG/Templates/Cycle2/Settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 sp2 (http://www.altova.com) by Peter Donker (Bring2mind) -->
<templateSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Settings.xsd">
 <templateSetting>
  <key>pager</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>allow-wrap</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>auto-height</key>
  <valueType>string</valueType>
  <defaultValue>0</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>delay</key>
  <valueType>integer</valueType>
  <defaultValue>0</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>fx</key>
  <valueType>dropdown</valueType>
  <values>
   <value>none</value>
   <value>fade</value>
   <value>fadeout</value>
   <value>scrollHorz</value>
  </values>
  <defaultValue>fade</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>loop</key>
  <valueType>integer</valueType>
  <defaultValue>0</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>pause-on-hover</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>random</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>reverse</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>speed</key>
  <valueType>integer</valueType>
  <defaultValue>1000</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>starting-slide</key>
  <valueType>integer</valueType>
  <defaultValue>0</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>swipe</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>sync</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>timeout</key>
  <valueType>integer</valueType>
  <defaultValue>4000</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>easing</key>
  <valueType>string</valueType>
  <defaultValue>null</defaultValue>
 </templateSetting>
</templateSettings>

=== donker/YAG/Templates/NivoSlider/Settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 sp2 (http://www.altova.com) by Peter Donker (Bring2mind) -->
<templateSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Settings.xsd">
 <templateSetting>
  <key>effect</key>
  <valueType>dropdown</valueType>
  <defaultValue>random</defaultValue>
  <values>
   <value>sliceDown</value>
   <value>sliceDownLeft</value>
   <value>sliceUp</value>
   <value>sliceUpLeft</value>
   <value>sliceUpDown</value>
   <value>sliceUpDownLeft</value>
   <value>fold</value>
   <value>fade</value>
   <value>random</value>
   <value>slideInRight</value>
   <value>slideInLeft</value>
   <value>boxRandom</value>
   <value>boxRain</value>
   <value>boxRainReverse</value>
   <value>boxRainGrow</value>
   <value>boxRainGrowReverse</value>
  </values>
 </templateSetting>
 <templateSetting>
  <key>slices</key>
  <valueType>integer</valueType>
  <defaultValue>15</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>boxCols</key>
  <valueType>integer</valueType>
  <defaultValue>8</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>boxRows</key>
  <valueType>integer</valueType>
  <defaultValue>4</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>animSpeed</key>
  <valueType>integer</valueType>
  <defaultValue>500</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>pauseTime</key>
  <valueType>integer</valueType>
  <defaultValue>3000</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>startSlide</key>
  <valueType>integer</valueType>
  <defaultValue>0</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>directionNav</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>directionNavHide</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>controlNav</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>controlNavThumbs</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>pauseOnHover</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>manualAdvance</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>prevText</key>
  <valueType>string</valueType>
  <defaultValue>Prev</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>nextText</key>
  <valueType>string</valueType>
  <defaultValue>Next</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>randomStart</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
</templateSettings>

=== donker/YAG/Templates/Slimbox2/Settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 sp2 (http://www.altova.com) by Peter Donker (Bring2mind) -->
<templateSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Settings.xsd">
 <templateSetting>
  <key>loop</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>overlayOpacity</key>
  <valueType>number</valueType>
  <defaultValue>0.8</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>overlayFadeDuration</key>
  <valueType>integer</valueType>
  <defaultValue>400</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>resizeDuration</key>
  <valueType>integer</valueType>
  <defaultValue>400</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>resizeEasing</key>
  <valueType>dropdown</valueType>
  <defaultValue>swing</defaultValue>
  <values>
   <value>swing</value>
   <value>linear</value>
  </values>
 </templateSetting>
 <templateSetting>
  <key>initialWidth</key>
  <valueType>integer</valueType>
  <defaultValue>250</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>initialHeight</key>
  <valueType>integer</valueType>
  <defaultValue>250</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>imageFadeDuration</key>
  <valueType>integer</valueType>
  <defaultValue>400</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>captionAnimationDuration</key>
  <valueType>integer</valueType>
  <defaultValue>400</defaultValue>
 </templateSetting>
</templateSettings>

=== donker/YAG/Templates/ResponsiveSlides/Settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 sp2 (http://www.altova.com) by Peter Donker (Bring2mind) -->
<templateSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Settings.xsd">
 <templateSetting>
  <key>auto</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>speed</key>
  <valueType>integer</valueType>
  <defaultValue>500</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>timeout</key>
  <valueType>integer</valueType>
  <defaultValue>4000</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>pager</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>nav</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>random</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>pause</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>pauseControls</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>prevText</key>
  <valueType>string</valueType>
  <defaultValue>Previous</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>nextText</key>
  <valueType>string</valueType>
  <defaultValue>Next</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>maxwidth</key>
  <valueType>string</valueType>
  <defaultValue></defaultValue>
 </templateSetting>
</templateSettings>

=== donker/YAG/Templates/NFLightbox/Settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 sp2 (http://www.altova.com) by Peter Donker (Bring2mind) -->
<templateSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Settings.xsd">
 <templateSetting>
  <key>overlayBgColor</key>
  <valueType>string</valueType>
  <defaultValue>#000</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>overlayOpacity</key>
  <valueType>integer</valueType>
  <defaultValue>8</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>fixedNavigation</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>imageLoading</key>
  <valueType>string</valueType>
  <defaultValue>images/loading.gif</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>imageBtnPrev</key>
  <valueType>string</valueType>
  <defaultValue>images/prev.png</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>imageBtnNext</key>
  <valueType>string</valueType>
  <defaultValue>images/next.png</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>imageBtnClose</key>
  <valueType>string</valueType>
  <defaultValue>images/close.png</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>imageBlank</key>
  <valueType>string</valueType>
  <defaultValue>images/lightbox-blank.gif</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>imageBtnBottomPrev</key>
  <valueType>string</valueType>
  <defaultValue>images/btm_prev.gif</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>imageBtnBottomNext</key>
  <valueType>string</valueType>
  <defaultValue>images/btm_next.gif</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>imageBtnPlay</key>
  <valueType>string</valueType>
  <defaultValue>images/start.png</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>imageBtnStop</key>
  <valueType>string</valueType>
  <defaultValue>images/pause.png</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>containerBorderSize</key>
  <valueType>integer</valueType>
  <defaultValue>10</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>containerResizeSpeed</key>
  <valueType>integer</valueType>
  <defaultValue>500</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>slideShowTimer</key>
  <valueType>integer</valueType>
  <defaultValue>5000</defaultValue>
 </templateSetting>
</templateSettings>

=== donker/YAG/Templates/_default/Settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<templateSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Settings.xsd">
 <templateSetting>
  <key>theme</key>
  <valueType>dropdown</valueType>
  <values>
   <value>dark_rounded</value>
   <value>dark_square</value>
   <value>default</value>
   <value>facebook</value>
   <value>light_rounded</value>
   <value>light_square</value>
  </values>
  <defaultValue>light_rounded</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>animation_speed</key>
  <valueType>dropdown</valueType>
  <values>
   <value>fast</value>
   <value>normal</value>
   <value>slow</value>
  </values>
  <defaultValue>normal</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>slideshow</key>
  <valueType>string</valueType>
  <defaultValue>5000</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>autoplay_slideshow</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>opacity</key>
  <valueType>string</valueType>
  <defaultValue>0.80</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>show_title</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>allow_resize</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>horizontal_padding</key>
  <valueType>integer</valueType>
  <defaultValue>20</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>autoplay</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>modal</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>overlay_gallery</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>keyboard_shortcuts</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
</templateSettings>

=== donker/YAG/Templates/Fancybox/Settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 sp2 (http://www.altova.com) by Peter Donker (Bring2mind) -->
<templateSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Settings.xsd">
 <templateSetting>
  <key>padding</key>
  <valueType>integer</valueType>
  <defaultValue>10</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>margin</key>
  <valueType>integer</valueType>
  <defaultValue>20</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>opacity</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>modal</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>cyclic</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>scrolling</key>
  <valueType>dropdown</valueType>
  <defaultValue>auto</defaultValue>
  <values>
   <value>auto</value>
   <value>yes</value>
   <value>no</value>
  </values>
 </templateSetting>
 <templateSetting>
  <key>width</key>
  <valueType>integer</valueType>
  <defaultValue>560</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>height</key>
  <valueType>integer</valueType>
  <defaultValue>340</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>autoScale</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>autoDimensions</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>centerOnScroll</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>swf</key>
  <valueType>string</valueType>
  <defaultValue>{wmode: 'transparent'}</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>hideOnOverlayClick</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>hideOnContentClick</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>overlayShow</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>overlayOpacity</key>
  <valueType>number</valueType>
  <defaultValue>0.3</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>overlayColor</key>
  <valueType>string</valueType>
  <defaultValue>#666</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>titleShow</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>titlePosition</key>
  <valueType>dropdown</valueType>
  <defaultValue>float</defaultValue>
  <values>
   <value>float</value>
   <value>outside</value>
   <value>inside</value>
   <value>over</value>
  </values>
 </templateSetting>
 <templateSetting>
  <key>titleFormat</key>
  <valueType>string</valueType>
  <defaultValue>null</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>transitionIn</key>
  <valueType>dropdown</valueType>
  <defaultValue>fade</defaultValue>
  <values>
   <value>fade</value>
   <value>elastic</value>
   <value>none</value>
  </values>
 </templateSetting>
 <templateSetting>
  <key>transitionOut</key>
  <valueType>dropdown</valueType>
  <defaultValue>fade</defaultValue>
  <values>
   <value>fade</value>
   <value>elastic</value>
   <value>none</value>
  </values>
 </templateSetting>
 <templateSetting>
  <key>speedIn</key>
  <valueType>integer</valueType>
  <defaultValue>300</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>speedOut</key>
  <valueType>integer</valueType>
  <defaultValue>300</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>changeSpeed</key>
  <valueType>integer</valueType>
  <defaultValue>300</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>changeFade</key>
  <valueType>dropdown</valueType>
  <defaultValue>fast</defaultValue>
  <values>
   <value>fast</value>
   <value>slow</value>
  </values>
 </templateSetting>
 <templateSetting>
  <key>easingIn</key>
  <valueType>dropdown</valueType>
  <defaultValue>swing</defaultValue>
  <values>
   <value>swing</value>
   <value>linear</value>
  </values>
 </templateSetting>
 <templateSetting>
  <key>easingOut</key>
  <valueType>dropdown</valueType>
  <defaultValue>swing</defaultValue>
  <values>
   <value>swing</value>
   <value>linear</value>
  </values>
 </templateSetting>
 <templateSetting>
  <key>showCloseButton</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>showNavArrows</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>enableEscapeButton</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
</templateSettings>

=== donker/YAG/Templates/Swiper/Settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<templateSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Settings.xsd">
 <templateSetting>
  <key>effect</key>
  <valueType>dropdown</valueType>
  <values>
   <value>slide</value>
   <value>fade</value>
   <value>cube</value>
   <value>overflow</value>
  </values>
  <defaultValue>slide</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>autoplay</key>
  <valueType>integer</valueType>
  <defaultValue>10000</defaultValue>
 </templateSetting>
</templateSettings>
