=== donker/YAG/Templates/Settings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 sp2 (http://www.altova.com) by Peter Donker (Bring2mind) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
 <xs:element name="templateSettings">
  <xs:annotation>
   <xs:documentation>Settings for the Gallery module</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:sequence>
    <xs:element name="templateSetting" minOccurs="0" maxOccurs="unbounded">
     <xs:complexType>
      <xs:all>
       <xs:element name="key" type="xs:string"/>
       <xs:element name="valueType">
        <xs:simpleType>
         <xs:restriction base="xs:string">
          <xs:enumeration value="string"/>
          <xs:enumeration value="dropdown"/>
          <xs:enumeration value="integer"/>
          <xs:enumeration value="truefalse"/>
          <xs:enumeration value="10"/>
          <xs:enumeration value="number"/>
         </xs:restriction>
        </xs:simpleType>
       </xs:element>
       <xs:element name="values" minOccurs="0">
        <xs:complexType>
         <xs:sequence>
          <xs:element name="value" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
         </xs:sequence>
        </xs:complexType>
       </xs:element>
       <xs:element name="defaultValue" type="xs:string"/>
      </xs:all>
     </xs:complexType>
    </xs:element>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
</xs:schema>

=== donker/YAG/Templates/Slippry/Settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<templateSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Settings.xsd">
 <templateSetting>
  <key>captions</key>
  <valueType>dropdown</valueType>
  <values>
   <value>overlay</value>
   <value>below</value>
   <value>custom</value>
   <value>none</value>
  </values>
  <defaultValue>overlay</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>responsive</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>pager</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>controls</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>transition</key>
  <valueType>dropdown</valueType>
  <values>
   <value>fade</value>
   <value>horizontal</value>
   <value>vertical</value>
   <value>kenburns</value>
   <value>none</value>
  </values>
  <defaultValue>fade</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>speed</key>
  <valueType>integer</valueType>
  <defaultValue>800</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>pause</key>
  <valueType>integer</valueType>
  <defaultValue>3000</defaultValue>
 </templateSetting>
</templateSettings>

=== donker/YAG/Templates/Masonry/Settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 sp2 (http://www.altova.com) by Peter Donker (Bring2mind) -->
<templateSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Settings.xsd">
 <templateSetting>
  <key>fx</key>
  <valueType>dropdown</valueType>
  <values>
   <value>none</value>
   <value>blindX</value>
   <value>blindY</value>
   <value>blindZ</value>
   <value>cover</value>
   <value>curtainX</value>
   <value>curtainY</value>
   <value>fade</value>
   <value>fadeZoom</value>
   <value>growX</value>
   <value>growY</value>
   <value>scollVert</value>
   <value>scrollDown</value>
   <value>scrollHorz</value>
   <value>scrollLeft</value>
   <value>scrollRight</value>
   <value>scrollUp</value>
   <value>shuffle</value>
   <value>slideX</value>
   <value>slideY</value>
   <value>toss</value>
   <value>turnDown</value>
   <value>turnLeft</value>
   <value>turnRight</value>
   <value>turnUp</value>
   <value>uncover</value>
   <value>wipe</value>
   <value>zoom</value>
  </values>
  <defaultValue>fade</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>autostop</key>
  <valueType>10</valueType>
  <defaultValue>0</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>autostopCount</key>
  <valueType>10</valueType>
  <defaultValue>0</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>backwards</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>cleartypeNoBg</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>containerResize</key>
  <valueType>10</valueType>
  <defaultValue>1</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>continuous</key>
  <valueType>10</valueType>
  <defaultValue>0</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>delay</key>
  <valueType>integer</valueType>
  <defaultValue>0</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>fastOnEvent</key>
  <valueType>integer</valueType>
  <defaultValue>0</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>fit</key>
  <valueType>10</valueType>
  <defaultValue>0</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>height</key>
  <valueType>string</valueType>
  <defaultValue>auto</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>manualTrump</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>nowrap</key>
  <valueType>10</valueType>
  <defaultValue>0</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>pause</key>
  <valueType>10</valueType>
  <defaultValue>0</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>random</key>
  <valueType>10</valueType>
  <defaultValue>0</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>randomizeEffects</key>
  <valueType>10</valueType>
  <defaultValue>1</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>requeueOnImageNotLoaded</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>requeueTimeout</key>
  <valueType>integer</valueType>
  <defaultValue>250</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>rev</key>
  <valueType>10</valueType>
  <defaultValue>0</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>slideResize</key>
  <valueType>10</valueType>
  <defaultValue>1</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>speed</key>
  <valueType>integer</valueType>
  <defaultValue>1000</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>sync</key>
  <valueType>10</valueType>
  <defaultValue>1</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>timeout</key>
  <valueType>integer</valueType>
  <defaultValue>4000</defaultValue>
 </templateSetting>
</templateSettings>

=== donker/YAG/Templates/Colorbox/Settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 sp2 (http://www.altova.com) by Peter Donker (Bring2mind) -->
<templateSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Settings.xsd">
 <templateSetting>
  <key>transition</key>
  <valueType>dropdown</valueType>
  <defaultValue>elastic</defaultValue>
  <values>
   <value>elastic</value>
   <value>fade</value>
   <value>none</value>
  </values>
 </templateSetting>
 <templateSetting>
  <key>speed</key>
  <valueType>integer</valueType>
  <defaultValue>350</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>title</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>width</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>height</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>innerWidth</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>innerHeight</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>initialWidth</key>
  <valueType>integer</valueType>
  <defaultValue>300</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>initialHeight</key>
  <valueType>integer</valueType>
  <defaultValue>100</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>maxWidth</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>maxHeight</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>scalePhotos</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>scrolling</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>photo</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>opacity</key>
  <valueType>number</valueType>
  <defaultValue>0.85</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>open</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>returnFocus</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>preloading</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>overlayClose</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>escKey</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>arrowKey</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>loop</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>slideshow</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>slideshowSpeed</key>
  <valueType>integer</valueType>
  <defaultValue>2500</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>slideshowAuto</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
</templateSettings>

=== donker/YAG/Templates/GalleryView/Settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 sp2 (http://www.altova.com) by Peter Donker (Bring2mind) -->
<templateSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Settings.xsd">
 <templateSetting>
  <key>transition_speed</key>
  <valueType>integer</valueType>
  <defaultValue>1000</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>transition_interval</key>
  <valueType>integer</valueType>
  <defaultValue>5000</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>easing</key>
  <valueType>dropdown</valueType>
  <defaultValue>swing</defaultValue>
  <values>
   <value>swing</value>
   <value>linear</value>
  </values>
 </templateSetting>
 <templateSetting>
  <key>show_panels</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>show_panel_nav</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>enable_overlays</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>panel_width</key>
  <valueType>integer</valueType>
  <defaultValue>800</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>panel_height</key>
  <valueType>integer</valueType>
  <defaultValue>400</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>panel_animation</key>
  <valueType>dropdown</valueType>
  <defaultValue>fade</defaultValue>
  <values>
   <value>crossfade</value>
   <value>fade</value>
   <value>slide</value>
   <value>none</value>
  </values>
 </templateSetting>
 <templateSetting>
  <key>panel_scale</key>
  <valueType>dropdown</valueType>
  <defaultValue>crop</defaultValue>
  <values>
   <value>crop</value>
   <value>fit</value>
  </values>
 </templateSetting>
 <templateSetting>
  <key>overlay_position</key>
  <valueType>dropdown</valueType>
  <defaultValue>bottom</defaultValue>
  <values>
   <value>bottom</value>
   <value>top</value>
  </values>
 </templateSetting>
 <templateSetting>
  <key>pan_images</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>pan_style</key>
  <valueType>dropdown</valueType>
  <defaultValue>drag</defaultValue>
  <values>
   <value>drag</value>
   <value>track</value>
  </values>
 </templateSetting>
 <templateSetting>
  <key>pan_smoothness</key>
  <valueType>integer</valueType>
  <defaultValue>15</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>start_frame</key>
  <valueType>integer</valueType>
  <defaultValue>1</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>show_filmstrip</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>show_filmstrip_nav</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>enable_slideshow</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>autoplay</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>show_captions</key>
  <valueType>truefalse</valueType>
  <defaultValue>false</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>filmstrip_size</key>
  <valueType>integer</valueType>
  <defaultValue>3</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>filmstrip_style</key>
  <valueType>dropdown</valueType>
  <defaultValue>scroll</defaultValue>
  <values>
   <value>scroll</value>
   <value>showall</value>
  </values>
 </templateSetting>
 <templateSetting>
  <key>filmstrip_position</key>
  <valueType>dropdown</valueType>
  <defaultValue>bottom</defaultValue>
  <values>
   <value>bottom</value>
   <value>top</value>
   <value>left</value>
   <value>right</value>
  </values>
 </templateSetting>
 <templateSetting>
  <key>frame_width</key>
  <valueType>integer</valueType>
  <defaultValue>80</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>frame_height</key>
  <valueType>integer</valueType>
  <defaultValue>40</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>frame_opacity</key>
  <valueType>number</valueType>
  <defaultValue>0.4</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>frame_scale</key>
  <valueType>dropdown</valueType>
  <defaultValue>crop</defaultValue>
  <values>
   <value>crop</value>
   <value>fit</value>
  </values>
 </templateSetting>
 <templateSetting>
  <key>frame_gap</key>
  <valueType>integer</valueType>
  <defaultValue>5</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>show_infobar</key>
  <valueType>truefalse</valueType>
  <defaultValue>true</defaultValue>
 </templateSetting>
 <templateSetting>
  <key>infobar_opacity</key>
  <valueType>number</valueType>
  <defaultValue>1</defaultValue>
 </templateSetting>
</templateSettings>
